= Simple Archive Script (uses rsync) 
:toc:

Creating backups can be a pain.  This script was put together to help keep
an archive of specific data in a seperate location than my normal backup
routine.  Why?

* All hardware fails eventually -- even the one(s) backups are written to.
* Simple mistakes can lead to backups becoming useless.

Ideally this should work on OS X and Linux (not currently tested).

== Why rsync?

It's a reliable tool that is readily available on Linux and OS X.  No need to
re-invent the wheel.  This script simply makes it easier to add directories as
needed.

== How Simple is It?

* One "archive" file for each "pair" of directories (source and destination).
* Optional single configuration file that only cares about logging, and applies
    to all pairs.
* Optional single "excludes" file for rsync that is applied to all pairs.

== So, What is Required?

The only real requirement is that the configuration directory
('~/.conf_simple_archive') exists for the script to run.  To create a directory
pair, simple create a bash snippit in a file that starts with 'arch_' in this
directory.

.'~/.conf_simple_archive/arch_example' example.
[source, bash]
----
SRC="/path/to/important/files/"
DST="/path/to/backup/location/for/important/files/"
----

WARNING:: Remember that that trailing slash is important to the way that rsync
          works.

NOTE:: A third variable (MNT_CHECK) can be used to determine that an external
        source is mounted.

== Logs

There are two variables that the script will use if they exist in the
configuration file.

.'~/.conf_simple_archive/conf' example.
[source, bash]
----
LOG_DIR="/path/to/store/log/files"
LOGS_PER_ARCH=25
----

The directory will be created if it does not already exist, and log files will
be stored here indefinitely by default.

The LOGS_PER_ARCH variable determines how many logs to keep in this directory.

== Example on Mac.

There is an example under examples/mac that includes:

* A
    https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html[Launch Agent]
    that will run every two hours.
* Using the 'MNT_CHECK' variable to see if an external volume is mounted.
* Logging to your home directory.

Note that to enable the 'Launch Agent' the following command will need to be
used once the file is in place.  This will not run the script immediately.
Instead it will be scheduled to run in two hours -- as defined by StartInterval.

.Enable Launch Agent.
[source, console]
----
$ launchctl load Library/LaunchAgents/local.simple_archive.plist
----

